name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build-and-test:
    uses: Sentience-Robotics/.github/.github/workflows/robot-package-ci.yaml@master
    with:
      package_name: so_arm101_urdf
      coverage_extra_paths: scripts
    secrets: inherit
